### ISSUE TITLE
Yarn Install Buildpack should only run "yarn install"

### ISSUE THREAD

**Issue by kvedurmu** [paketo-buildpacks/yarn-install#99]
As per the [Node.js re-architecture RFC](https://github.com/paketo-buildpacks/nodejs/blob/main/rfcs/0001-buildpacks-architecture.md), once https://github.com/paketo-buildpacks/nodejs/issues/205 and https://github.com/paketo-buildpacks/nodejs/issues/204 are implemented, we should update this buildpack to only run `yarn install`. After this is complete, Language family ordering will look like:
```
[[order]]

  [[order.group]]
    id = "paketo-buildpacks/node-engine"

  [[order.group]]
    id = "paketo-buildpacks/yarn"

  [[order.group]]
    id = "paketo-buildpacks/yarn-install"

  [[order.group]]
    id = "paketo-buildpacks/tini"

  [[order.group]]
    id = "paketo-buildpacks/yarn-start"
......
[[order]]

  [[order.group]]
    id = "paketo-buildpacks/node-engine"

  [[order.group]]
    id = "paketo-buildpacks/node-start"
```

**Comment by joshzarrabi** [comment]
Done here: https://github.com/paketo-buildpacks/yarn-install/commit/7f1f41a88366445234bb92021e3899d1b7337546
